<?php
/**
 * This file has been automaticaly generated by Pomm Cli package.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\Bobinaudio\TransfoSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * EiDimension
 *
 * Structure class for relation transfo.ei_dimension.
 * Standard supported transformers sizes.
 *
 *
 *
 * @see RowStructure
 */
class EiDimension extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('transfo.ei_dimension')
            ->setPrimaryKey(['ei_dimension_id'])
            ->addField('ei_dimension_id', 'int4')
            ->addField('ref', 'varchar')
            ->addField('len_a', 'int4')
            ->addField('len_b', 'int4')
            ->addField('len_c', 'int4')
            ->addField('diameter', 'numeric')
            ->addField('average_h', 'int4')
            ;
    }
}
