<?php
/**
 * This file has been automaticaly generated by Pomm Cli package.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\Bobinaudio\TransfoSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Inductance
 *
 * Structure class for relation transfo.inductance.
 * Table for selfs, aka inductances.
 *
 *
 *
 * @see RowStructure
 */
class Inductance extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('transfo.inductance')
            ->setPrimaryKey(['transformer_id'])
            ->addField('transformer_id', 'uuid')
            ->addField('ref', 'varchar')
            ->addField('ei_dimension_id', 'int4')
            ->addField('weight', 'numeric')
            ->addField('height', 'int4')
            ->addField('meta', 'json')
            ->addField('is_online', 'bool')
            ->addField('is_on_top', 'bool')
            ->addField('is_advertised', 'bool')
            ->addField('display_order', 'int4')
            ->addField('pri', 'transfo.winding')
            ->addField('inductance', 'numeric')
            ->addField('hook_phrase_i18n', 'public.hstore')
            ->addField('description_i18n', 'public.hstore')
            ->addField('pri_idc', 'int4')
            ;
    }
}
